LAST_NODE_ID = 1000
LAST_BUFFER_ID = 0
RESPONSE_TIMEOUT = 1.0

ADD_TO_HEAD = "addToHead"
ADD_TO_TAIL = "addToTail"
ADD_AFTER = "addAfter"
ADD_BEFORE = "addBefore"
ADD_REPLACE = "addReplace"

HEADER_FORMAT_WAV = "wav"
HEADER_FORMAT_AIFF = "aiff"
HEADER_FORMAT_RAW = "raw"
HEADER_FORMAT_IRCAM = "ircam"
HEADER_FORMAT_NEXT = "next"

SAMPLE_FORMAT_INT8 = "int8"
SAMPLE_FORMAT_INT16 = "int16"
SAMPLE_FORMAT_INT24 = "int24"
SAMPLE_FORMAT_INT32 = "int32"
SAMPLE_FORMAT_FLOAT = "float"
SAMPLE_FORMAT_DOUBLE = "double"
SAMPLE_FORMAT_MULAW = "mulaw"
SAMPLE_FORMAT_ALAW = "alaw"